---
title: "Homework 5"
author: "Kimberly Kreitner"
date: "11/27/2021"
output:
  pdf_document: default
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tigris_use_cache = TRUE)
```


``` {r packages}
library(tidyverse)
library(readr)
library(dplyr)
library(stringr)
```


``` {r data}
# setwd("~/Google Drive (kreitnerki@utexas.edu)/PHD/Fall2021/R programming/homework/rclassexercises")
homicide_data <- read_csv("data/homicide-data.csv")
```

# Choice 1

``` {r choice 1 setup}
library(sf)
library(tigris)
```

## City Selected is Baltimore
``` {r select city}
homicide_data <- homicide_data %>%
  mutate(city_name = paste(city, ",", state)) %>%
  filter(city_name == "Baltimore , MD") %>%
  mutate(disposition_new = disposition %in% c("Open/No arrest",
                                              "Closed without arrest")) %>%
  mutate(disposition_num = as.integer(disposition_new)) %>%
  group_by(victim_race)
head(homicide_data)
```

## Baltimore, MD Map
``` {r map attempt}
library(ggplot2)
b_homicides <- st_as_sf(homicide_data, coords = c("lon", "lat"))%>%
  st_set_crs(4269)
b_homicides %>% slice(1:3)
```

``` {r homicide specifics}
library(forcats)
table(homicide_data$victim_race)
top_race <- homicide_data %>%
  filter(victim_race %in% c("Black", "Hispanic", "White")) %>%
  st_as_sf(coords = c("lon", "lat"))%>%
  st_set_crs(4269)
```

``` {r baltimore}

md_counties <- counties(state = "MD", cb = TRUE, class = "sf")
baltimore <- md_counties %>%
  filter(NAME == "Baltimore", COUNTYFP == "510")
b_blocks <- blocks("MD", 510)
plot(b_blocks)
class(md_counties)
class(baltimore)
```

``` {r baltimorehomicide map}
ggplot()+
  geom_sf(data = b_blocks) +
  geom_sf(data = top_race, aes(color = victim_race) +
  facet_grid(~ disposition_num) +
  theme_classic() +
  ggtitle("Homicide Events in Baltimore, Maryland")
```
